# Logstash Pipeline — Windows Logs
# SOC Tier 1 ESAIP — Fèmi KPONOU

input {
  beats {
    port => 5044
    host => "0.0.0.0"
  }
}

filter {
  if [agent][type] == "winlogbeat" {

    # Parse Windows Security Events
    if [winlog][channel] == "Security" {
      mutate {
        add_field => { "log_source" => "windows_security" }
      }

      # Logon events
      if [winlog][event_id] == 4624 {
        mutate { add_tag => ["logon_success"] }
      }
      if [winlog][event_id] == 4625 {
        mutate { add_tag => ["logon_failure"] }
      }
      # Privilege use
      if [winlog][event_id] == 4672 {
        mutate { add_tag => ["privilege_escalation"] }
      }
    }

    # Parse Sysmon Events
    if [winlog][channel] == "Microsoft-Windows-Sysmon/Operational" {
      mutate {
        add_field => { "log_source" => "sysmon" }
      }
      # Process creation
      if [winlog][event_id] == 1 {
        mutate { add_tag => ["process_creation"] }
      }
      # Network connection
      if [winlog][event_id] == 3 {
        mutate { add_tag => ["network_connection"] }
      }
    }

    # GeoIP enrichment
    if [source][ip] {
      geoip {
        source => "[source][ip]"
        target => "source_geo"
      }
    }

    # MITRE ATT&CK tagging
    if "process_creation" in [tags] {
      mutate { add_field => { "mitre_tactic" => "Execution" } }
    }
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "soc-windows-%{+YYYY.MM.dd}"
  }
}